name: mealup
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+7

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.6
#without null safety
#  flutter_svg: ^0.19.0
  flutter_svg: ^0.22.0
  #rating_bar: ^0.2.0
  flutter_rating_bar: ^4.0.0
  dotted_line: ^3.0.0
  # flutter_share: ^1.0.2+1
  share: ^2.0.4
  flutter_screenutil: ^5.0.0+2
  # google_maps_flutter: ^2.0.11
  google_maps_flutter: ^2.1.1
  location: ^4.3.0
  #without null safety
  #  dotted_border: ^1.0.6
  dotted_border: ^2.0.0
  http: ^0.13.3
  uuid: ^3.0.4
  retrofit: ^2.0.0
  logger: ^1.0.0
  #fluttertoast: ^8.0.8
#  country_code_picker: ^1.6.2
  country_code_picker: ^2.0.2
 # progress_dialog: ^1.2.4
#  sn_progress_dialog: ^1.0.2
  # simple_fontellico_progress_dialog: ^0.2.0
  flutter_spinkit: ^5.0.0
  #without null safety
  cached_network_image: ^3.0.0
#  cached_network_image: ^3.0.0
  #old
  #geocoder: ^0.2.1
  geocoding: ^2.0.1
  geolocator: ^7.7.1
  connectivity: ^3.0.6
  #without null safety
#  flutter_widget_from_html: ^0.5.1+5
#  flutter_widget_from_html: ^0.6.0
  flutter_html: ^2.1.0
  scoped_model: ^2.0.0-nullsafety.0
  # razorpay_flutter: ^1.2.7
#  stripe_payment: ^1.1.4
  flutter_stripe: ^2.0.1
  sqflite: ^2.0.0+3
  path: ^1.8.0
  onesignal_flutter: ^3.2.5
  flutter_credit_card: ^2.0.0
  #modal_progress_hud: ^0.1.3
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  # flutter_multi_formatter: ^2.3.1
 # credit_card_number_validator: ^1.0.4
  flutter_localizations:
    sdk: flutter
  http_auth: ^1.0.0
  #without null safety
#  pull_to_refresh: ^1.6.3
  pull_to_refresh: ^2.0.0
  webview_flutter: ^2.0.10
  url_launcher: ^6.0.9
  image_picker: ^0.8.2
  modal_bottom_sheet: ^2.0.0
  flutter_polyline_points: ^1.0.0
  carousel_slider: ^4.0.0
#  flutter_math_fork: ^0.6.0
  google_maps_place_picker:
    git:
      url: https://github.com/radhen-thirstydevs/google_maps_place_picker.git
      ref: google_maps_place_picker_provider_update
#      ref: google_maps_place_picker_temp

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^2.0.0+3
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/ic_app_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Proxima
       fonts:
         - asset: fonts/ProximaNova-Regular.otf

     - family: ProximaBold
       fonts:
         - asset: fonts/Proxima Nova Bold.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
